<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/2025_DT_read_cloud_1141husthorng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#

import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)
worksheet = gc.open('2025_DT 的副本').sheet1
records = pd.read_excel('https://docs.google.com/spreadsheets/d/e/2PACX-1vT1fsVI46ixmI5Fb8bwTKrhkcWajupllMcaYHv2waOct-gpv3P-Ej0IVQlrUZqAj1rYP45wlUkJKcK2/pub?output=xlsx')
#https://docs.google.com/spreadsheets/d/1cnAI9KTv0NAFCrJ5iHXF0DFSj1LxxvkllSXd6Z5Dtg0/edit?gid=0#gid=0
#neural_networks_3_1_cloud.zip https://drive.google.com/file/d/1pzKNlR7pe5zEOvehfiOT1WJ2_C7pqWw3/view?usp=drive_link

numTag=1
hidden_node=3

inputD=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
print(inputD.shape)
tagetD=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values
print(inputD)
print(tagetD)

np.random.seed(1)
syn0=2*np.random.random((inputD.shape[1],hidden_node))-1
syn1=2*np.random.random((hidden_node,numTag))-1

def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A

for j in range(1200):
    X=inputD
    L0=nonlin(np.dot(inputD,syn0))
    L1=nonlin(np.dot(L0,syn1))
    #print(L1)
    L1_error=tagetD-L1
    if(j % 10)==0:
        print("Error"+str(np.mean(np.abs(L1_error))))
    #print(L1_error)
    L1_delta=L1_error*nonlin(L1,deriv=True)
    #print(L1_delta)
    L0_error=L1_delta.dot(syn1.T)
    L0_delta=L0_error*nonlin(L0,deriv=True)
    syn1 += L0.T.dot(L1_delta)
    syn0 += inputD.T.dot(L0_delta)

print("output after Training:")
# np.savetxt("syn0.csv", syn0, delimiter=",")
# np.savetxt("syn1.csv", syn1, delimiter=",")
#print(syn0)

df0 = pd.DataFrame(syn0.transpose())


df0.to_csv("syn0.csv")
df1 = pd.DataFrame(syn1.transpose())
df1.to_csv("syn1.csv")
print(L1)
print(syn0)
print(syn0.transpose())
print(syn1)

# Open our new sheet and add some data.
worksheet = gc.open("2025_DT 的副本").worksheet("W0")

worksheet.update_acell('A1', records.shape[1]-numTag)
worksheet.update_acell('B1', hidden_node)
worksheet.update(df0.values.tolist(), 'A2')



worksheet = gc.open("2025_DT 的副本").worksheet("W1")
worksheet.update(df1.values.tolist(), 'A2')
worksheet.update_acell('A1', numTag)
worksheet.update_acell('B1', hidden_node)


(4, 3)
[[0 0 1]
 [1 0 1]
 [1 1 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]
Error0.5108456683181672
Error0.4982751769591847
Error0.48515698572956134
Error0.46118561235577704
Error0.41773650978735105
Error0.3530248712432166
Error0.27568852450850967
Error0.20456877195029627
Error0.15147472336885734
Error0.11508255629042652
Error0.09030563422437302
Error0.07303521590581306
Error0.060613050953511584
Error0.05139640659850055
Error0.04436346311147878
Error0.03886335583125783
Error0.03446951326269466
Error0.03089426368007204
Error0.027938331461332643
Error0.025460246764626937
Error0.02335732624713261
Error0.021553537767196047
Error0.019991564522360124
Error0.018627495043739246
Error0.017427194218245214
Error0.016363774480908165
Error0.01541580193974047
Error0.014566002850663874
Error0.01380031675966117
Error0.013107193754127725
Error0.012477066198851212
Error0.011901946930664032
Error0.01137512028983222
Error0.010890902123512503
Error0.010444451603340395
Error0.010031622372443679
Error0.0096488438352986

{'spreadsheetId': '1cnAI9KTv0NAFCrJ5iHXF0DFSj1LxxvkllSXd6Z5Dtg0',
 'updatedRange': "'W1'!B1",
 'updatedRows': 1,
 'updatedColumns': 1,
 'updatedCells': 1}

In [ ]:
records.shape[0]

4

In [ ]:

df0

0         1         2
0  -3.866911 -0.167075 -0.070278
1   7.409210 -1.980814 -2.950023
2 -11.778420 -0.366808  0.904531

In [ ]:
print(df1.values.tolist())

[[-3.264403191053369, 6.438038319219514, -7.2555353905945905]]
