<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/arrayDot_TR33_CSWP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

worksheet = gc.open("2025_DT hung").worksheet("tr33")
#https://docs.google.com/spreadsheets/d/1Da3N9N31SI-ZMF6ucIH4WwdjpX3V_kQx2ya_f8IJfVQ/edit?usp=sharing

rows = worksheet.get_all_values()
print(rows)
rows.pop(0)    #刪除第一列
records = pd.DataFrame(rows) #轉pandas結構
inputD=records.iloc[:,0:3]
records1 = np.array(inputD)
print(records1)
test = records1.astype(int)
test


[['PB1', 'PB2', 'PB3', 'TL1', 'TL2', 'TL3'], ['0', '0', '0', '0', '0', '1'], ['1', '0', '0', '0', '1', '0'], ['0', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '0', '1'], ['1', '1', '0', '1', '0', '0'], ['0', '1', '1', '0', '0', '1'], ['1', '1', '1', '1', '0', '0']]
[['0' '0' '0']
 ['1' '0' '0']
 ['0' '1' '0']
 ['0' '0' '1']
 ['1' '1' '0']
 ['0' '1' '1']
 ['1' '1' '1']]


array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [25]:
import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

worksheet = gc.open("2025_DT hung").worksheet("test")
rows = worksheet.get_all_values()
print(rows)
records = pd.DataFrame(rows) #轉pandas結構

rows.pop(0)    #刪除第一列
records1 = np.array(rows)
print(records1)
test = records1.astype(int)
test

[['PB1', 'PB2', 'PB3'], ['0', '0', '0'], ['1', '0', '0'], ['0', '1', '0'], ['0', '0', '1'], ['1', '1', '0'], ['0', '1', '1'], ['1', '1', '1']]
[['0' '0' '0']
 ['1' '0' '0']
 ['0' '1' '0']
 ['0' '0' '1']
 ['1' '1' '0']
 ['0' '1' '1']
 ['1' '1' '1']]


array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [26]:
worksheet = gc.open("2025_DT hung").worksheet("tr33W0")
rows = worksheet.get_all_values()
print(rows)
records = pd.DataFrame(rows) #轉pandas結構

rows.pop(0)    #刪除第一列
W0 = np.array(rows)
W0 = W0.astype(float)

W0

[['3', '13', ''], ['-11.94559012', '-3.472589429', '-1.807080141'], ['-3.595073705', '-32.7335453', '-8.796216728'], ['-16.81558842', '-3.660069393', '-1.701277147'], ['-28.04120791', '-1.362256154', '0.1733875466'], ['-32.24784841', '-1.080419563', '-0.987800226'], ['-37.00094858', '-1.19688276', '0.1343690661'], ['-29.17579057', '-2.467389618', '0.8349088292'], ['-37.68495071', '-1.342224736', '0.02328338534'], ['-32.10065755', '33.48404729', '6.904844092'], ['-26.29284985', '-2.257291317', '-0.4643880705'], ['28.64143296', '-17.06554036', '-7.815136117'], ['-0.09473437937', '-5.587400767', '2.593253804'], ['-15.6876362', '-4.112926497', '-2.242083069']]


array([[-1.19455901e+01, -3.47258943e+00, -1.80708014e+00],
       [-3.59507370e+00, -3.27335453e+01, -8.79621673e+00],
       [-1.68155884e+01, -3.66006939e+00, -1.70127715e+00],
       [-2.80412079e+01, -1.36225615e+00,  1.73387547e-01],
       [-3.22478484e+01, -1.08041956e+00, -9.87800226e-01],
       [-3.70009486e+01, -1.19688276e+00,  1.34369066e-01],
       [-2.91757906e+01, -2.46738962e+00,  8.34908829e-01],
       [-3.76849507e+01, -1.34222474e+00,  2.32833853e-02],
       [-3.21006576e+01,  3.34840473e+01,  6.90484409e+00],
       [-2.62928498e+01, -2.25729132e+00, -4.64388071e-01],
       [ 2.86414330e+01, -1.70655404e+01, -7.81513612e+00],
       [-9.47343794e-02, -5.58740077e+00,  2.59325380e+00],
       [-1.56876362e+01, -4.11292650e+00, -2.24208307e+00]])

In [27]:
worksheet = gc.open("2025_DT hung").worksheet("tr33W1")
rows = worksheet.get_all_values()
print(rows)
records = pd.DataFrame(rows) #轉pandas結構

rows.pop(0)    #刪除第一列
W1 = np.array(rows)
W1 = W1.astype(float)

W1

[['3', '13', '', '', '', '', '', '', '', '', '', '', ''], ['-8.861896126', '-10.47179683', '-3.293415504', '-12.13224239', '-13.04371708', '-11.70049816', '-6.061185069', '-9.888721116', '4.665430921', '-6.786811186', '3.310037168', '-20.1544887', '-3.183638674'], ['-0.465244312', '5.302506282', '-0.8957810629', '-3.007159161', '-2.924927752', '-2.850776532', '-1.961854787', '-2.620938747', '-15.11027595', '-1.46791926', '4.576658344', '4.406066289', '-0.8588466493'], ['1.833402508', '-2.433970981', '1.966419915', '4.14857245', '5.398251896', '5.303307354', '3.740369798', '5.195293993', '3.622502209', '4.200135886', '-11.98868923', '-3.282413893', '1.578268255']]


array([[ -8.86189613, -10.47179683,  -3.2934155 , -12.13224239,
        -13.04371708, -11.70049816,  -6.06118507,  -9.88872112,
          4.66543092,  -6.78681119,   3.31003717, -20.1544887 ,
         -3.18363867],
       [ -0.46524431,   5.30250628,  -0.89578106,  -3.00715916,
         -2.92492775,  -2.85077653,  -1.96185479,  -2.62093875,
        -15.11027595,  -1.46791926,   4.57665834,   4.40606629,
         -0.85884665],
       [  1.83340251,  -2.43397098,   1.96641991,   4.14857245,
          5.3982519 ,   5.30330735,   3.7403698 ,   5.19529399,
          3.62250221,   4.20013589, -11.98868923,  -3.28241389,
          1.57826826]])

In [28]:
L0s=np.dot(test, W0.T)
L0s

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.19455901e+01, -3.59507370e+00, -1.68155884e+01,
        -2.80412079e+01, -3.22478484e+01, -3.70009486e+01,
        -2.91757906e+01, -3.76849507e+01, -3.21006576e+01,
        -2.62928498e+01,  2.86414330e+01, -9.47343794e-02,
        -1.56876362e+01],
       [-3.47258943e+00, -3.27335453e+01, -3.66006939e+00,
        -1.36225615e+00, -1.08041956e+00, -1.19688276e+00,
        -2.46738962e+00, -1.34222474e+00,  3.34840473e+01,
        -2.25729132e+00, -1.70655404e+01, -5.58740077e+00,
        -4.11292650e+00],
       [-1.80708014e+00, -8.79621673e+00, -1.70127715e+00,
         1.73387547e-01, -9.87800226e-01,  1.34369066e-01,
         8.34908829e-01,  2.32833853e-02,  6.90484409e+00,
        -4.64388071e-01, -7.81513612e

In [29]:
def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A

In [30]:
L0=nonlin(L0s)
L0

array([[5.00000000e-01, 5.00000000e-01, 5.00000000e-01, 5.00000000e-01,
        5.00000000e-01, 5.00000000e-01, 5.00000000e-01, 5.00000000e-01,
        5.00000000e-01, 5.00000000e-01, 5.00000000e-01, 5.00000000e-01,
        5.00000000e-01],
       [6.48773811e-06, 2.67248312e-02, 4.97831895e-08, 6.63526296e-13,
        9.88410573e-15, 8.52495719e-17, 2.13361055e-13, 4.30163796e-17,
        1.14514785e-14, 3.81206587e-12, 1.00000000e+00, 4.76334102e-01,
        1.53796374e-07],
       [3.01022881e-02, 6.08137666e-15, 2.50852650e-02, 2.03873863e-01,
        2.53426626e-01, 2.32030220e-01, 7.81761443e-02, 2.07144440e-01,
        1.00000000e+00, 9.47223838e-02, 3.87730508e-08, 3.73077787e-03,
        1.60964916e-02],
       [1.40991388e-01, 1.51281530e-04, 1.54298536e-01, 5.43238616e-01,
        2.71346793e-01, 5.33541815e-01, 6.97391874e-01, 5.05820583e-01,
        9.98998089e-01, 3.85945369e-01, 4.03417071e-04, 9.30426142e-01,
        9.60345543e-02],
       [2.01358336e-07, 1.66986450e-

In [31]:
L1s=np.dot(L0, W1.T)
L1s

array([[-48.80147137,  -8.93924665,   9.64072508],
       [ -6.57014826,   6.81712336, -13.61725013],
       [ -7.46942394, -17.99526794,   8.95098281],
       [-44.37617164, -18.4879874 ,  14.67851487],
       [  6.9717602 ,  -7.48961969,  -9.10340236],
       [ -7.15904865, -17.634975  ,   8.39043955],
       [  7.02093888, -10.44191455,  -8.23751822]])

In [32]:
L1=nonlin(L1s)
L1

array([[6.39425974e-22, 1.31122602e-04, 9.99934978e-01],
       [1.39962790e-03, 9.98906331e-01, 1.21927840e-06],
       [5.69931694e-04, 1.53022195e-08, 9.99870407e-01],
       [5.34162664e-20, 9.34908451e-09, 9.99999578e-01],
       [9.99062879e-01, 5.58543314e-04, 1.11274143e-04],
       [7.77189660e-04, 2.19395472e-08, 9.99773024e-01],
       [9.99107810e-01, 2.91824302e-05, 2.64470002e-04]])

In [33]:
result = (L1 > 0.9).astype(int)
result

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0]])