<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/backpropagation_4x1y.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

import csv
import pandas as pd

numTag=1   #   輸出的數目
nnode=4
url = "exdata4X1y.csv"
records = pd.read_csv(url,encoding='utf-8',header=None)
Xi=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
y=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values

X=np.insert(Xi,Xi[0].size,1,axis=1)
np.random.seed(1)
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((X[0].size,nnode)) - 1
syn1 = 2*np.random.random((nnode+1,numTag)) - 1

for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l1=np.insert(l1,l1[0].size,1,axis=1)
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))

    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)

    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)[:,:-1]

#print output
print("output after Training:")
print(l2)

Error:0.4477946282344683
Error:0.0075239768071326185
Error:0.00521795987206721
Error:0.0042246520914848516
Error:0.00364019793220164
Error:0.003244530501107492
output after Training:
[[0.99530571]
 [0.00156105]
 [0.99774898]
 [0.00478684]
 [0.00364312]
 [0.9987647 ]
 [0.99749282]]


In [ ]:
syn0

array([[ 2.46369755, -0.07387711, -5.45829067, -1.1241206 ],
       [-0.59686426, -6.12266817, -1.30806974,  0.6301363 ],
       [-1.96885316,  1.3139501 ,  2.33120362,  2.09189883],
       [-2.53878217, -4.75064777, -7.545376  ,  1.33353025],
       [-0.08084971,  6.8113164 ,  1.09097013, -0.14344953]])

In [ ]:
syn1

array([[  3.19787556],
       [ 12.23544219],
       [-12.64151003],
       [ -3.8237726 ],
       [ -2.61913888]])