<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/dht_run_cswp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#


import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)
WID="15sOASk3jTVCQNy6O-zwed0PXGIiE9JEB4PNc8H3XFcY"

def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A

worksheet =gc.open_by_key(WID).worksheet("tr33W0") #2025_DT hung 111husthorng

rows = worksheet.get_all_values()
inputnode = int(rows[0][0])
hiddennode=int(rows[0][1])
rows.pop(0)
np.array(rows, dtype=float)
syn0 = np.array(rows, dtype=float)

worksheet =gc.open_by_key(WID).worksheet("tr33W1") #2025_DT hung 111husthorng
rows = worksheet.get_all_values()
outputnode = int(rows[0][0])
rows.pop(0)
syn1 = np.array(rows, dtype=float)
OX=[]

while True :

  # ⚠️ 出現錯誤時避開並繼續執行
  try:

      worksheet =gc.open_by_key(WID).worksheet("input") #2025_DT hung 111husthorng
      X = worksheet.get("A1:C1")
      X = np.array(X[0], dtype=float)
      print(X)

      CPL0 = np.dot(X, syn0.T)
      print(CPL0)
      L0 = nonlin(np.dot(X, syn0.T))
      print(L0)

      CPL1 = np.dot(L0, syn1.T)
      print(CPL1)

      L1 = nonlin(np.dot(L0, syn1.T))
      print(L1)
      L1 = (L1 > 0.9).astype(int)
      print(L1)



#      worksheet = gc.open("DT output").worksheet("output")
      worksheet.update('I1:K1', [L1.tolist()])
  except Exception as e:
      print("⚠️ 更新失敗：", e)
      # 可依需要延遲一段時間避免連續錯誤
      import time
      time.sleep(1)
      continue

[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]


/tmp/ipython-input-914485123.py:64: DeprecationWarning: The order of arguments in worksheet.update() has changed. Please pass values first and range_name secondor used named arguments (range_name=, values=)
  worksheet.update('I1:K1', [L1.tolist()])


[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01

KeyboardInterrupt: 