<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/DT_run.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#


import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A



worksheet = gc.open("2025_DT hung").worksheet("tr33W0")
rows = worksheet.get_all_values()
inputnode = int(rows[0][0])
hiddennode=int(rows[0][1])
rows.pop(0)
np.array(rows, dtype=float)
syn0 = np.array(rows, dtype=float)

worksheet = gc.open("2025_DT hung").worksheet("tr33W1")
rows = worksheet.get_all_values()
outputnode = int(rows[0][0])
rows.pop(0)
syn1 = np.array(rows, dtype=float)
OX=[]

while True :

  # ⚠️ 出現錯誤時避開並繼續執行
  try:
      worksheet = gc.open("2025_DT hung").worksheet("input")

      X = worksheet.get("A1:C1")
      X = np.array(X[0], dtype=float)
      print(X)

      CPL0 = np.dot(X, syn0.T)
      print(CPL0)
      L0 = nonlin(np.dot(X, syn0.T))
      print(L0)

      CPL1 = np.dot(L0, syn1.T)
      print(CPL1)

      L1 = nonlin(np.dot(L0, syn1.T))
      print(L1)
      L1 = (L1 > 0.9).astype(int)
      print(L1)



#      worksheet = gc.open("DT output").worksheet("output")
      worksheet.update('I1:K1', [L1.tolist()])
  except Exception as e:
      print("⚠️ 更新失敗：", e)
      # 可依需要延遲一段時間避免連續錯誤
      import time
      time.sleep(1)
      continue

[1. 1. 0.]
[-15.41817955 -36.32861901 -20.47565781 -29.40346406 -33.32826797
 -38.19783134 -31.64318019 -39.02717545   1.38338974 -28.55014117
  11.5758926   -5.68213515 -19.8005627 ]
[2.01358336e-07 1.66986450e-16 1.28095773e-09 1.69917382e-13
 3.35519007e-15 2.57568429e-17 1.80942862e-14 1.12386219e-17
 7.99534856e-01 3.98869872e-13 9.99990610e-01 3.39471443e-03
 2.51608252e-09]
[ 6.9717602  -7.48961969 -9.10340236]
[9.99062879e-01 5.58543314e-04 1.11274143e-04]
[1 0 0]


/tmp/ipython-input-2526982197.py:64: DeprecationWarning: The order of arguments in worksheet.update() has changed. Please pass values first and range_name secondor used named arguments (range_name=, values=)
  worksheet.update('I1:K1', [L1.tolist()])


Streaming output truncated to the last 5000 lines.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]
⚠️ 更新失敗： APIError: [429]: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.co

In [ ]:
worksheet = gc.open("2025_DT 的副本").worksheet("input")

X = worksheet.get("A1:C1")


X=np.array(X[0], dtype=float)
print(X)
CPL0=np.dot(X,syn0.T)
print(CPL0)
L0=nonlin(np.dot(X,syn0.T))
print(L0)


CPL1=np.dot(L0,syn1.T)
print(CPL1)

L1=nonlin(np.dot(L0,syn1.T))
print(L1)
L1= (L1 > 0.9).astype(int)
print(L1)

[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]
[0 0 1]


In [ ]:
#


import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A



worksheet = gc.open("2025_DT 的副本").worksheet("tr33W0")
rows = worksheet.get_all_values()
inputnode = int(rows[0][0])
hiddennode=int(rows[0][1])
rows.pop(0)
np.array(rows, dtype=float)
syn0 = np.array(rows, dtype=float)

worksheet = gc.open("2025_DT 的副本").worksheet("tr33W1")
rows = worksheet.get_all_values()
outputnode = int(rows[0][0])
rows.pop(0)
syn1 = np.array(rows, dtype=float)
OX=[]
while True :

  worksheet = gc.open("2025_DT 的副本").worksheet("input")

  X = worksheet.get("A1:C1")


  X=np.array(X[0], dtype=float)
  print(X)
  CPL0=np.dot(X,syn0.T)
  print(CPL0)
  L0=nonlin(np.dot(X,syn0.T))
  print(L0)


  CPL1=np.dot(L0,syn1.T)
  print(CPL1)

  L1=nonlin(np.dot(L0,syn1.T))
  print(L1)


  #if (L1 >= 0.9 ):
  #    output=1
  #elif (L1 <= 0.2):
  #    output=0
  #else : output=9

  print(output)


  #worksheet = gc.open(2025_DT 的副本").worksheet("input")

  worksheet.update([[output]], 'F1')
#syn00 = worksheet.get("A2:C4")

[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[-48.80147137  -8.93924665   9.64072508]
[6.39425974e-22 1.31122602e-04 9.99934978e-01]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
rows


[['-3.264403191', '6.438038319', '-7.255535391']]

In [ ]:
hiddennode

3

In [ ]:

W1_list = [[float(x) for x in row] for row in rows]

In [ ]:
resure=[[float(x) for x in row] for row in rows]

ValueError: could not convert string to float: ''

In [ ]:
records1 = np.array(rows, dtype=int)  #將字元['1']換成數字[1]

ValueError: invalid literal for int() with base 10: ''

In [ ]:
rows

[['3', '3', ''],
 ['-3.866911155', '-0.1670752832', '-0.07027842194'],
 ['7.409209907', '-1.980814056', '-2.950022942'],
 ['-11.77842005', '-0.3668075118', '0.9045307296']]

In [ ]:
#


import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A



worksheet = gc.open("2025_DT 的副本").worksheet("W0")


syn00 = worksheet.get("A2:C4")
#worksheet = gc.open("2025_DT 的副本").worksheet("W0")
# get_all_values gives a list of rows.

#syn00 = worksheet.get("A1:D3")
syn0=np.array(syn00, dtype=float)
print(syn0)

worksheet = gc.open("2025_DT 的副本").worksheet("W1")
syn11 = worksheet.get("A2:C2")
#worksheet = gc.open("2025_DT").worksheet("W1")
#syn11 = worksheet.get("A1:C1")

syn1=np.array(syn11[0], dtype=float)
print(syn1)
OX=[]
while True :

  worksheet = gc.open("2025_DT 的副本").worksheet("input")

  X = worksheet.get("A1:C1")


  X=np.array(X[0], dtype=float)
  print(X)
  CPL0=np.dot(X,syn0.T)
  print(CPL0)
  L0=nonlin(np.dot(X,syn0.T))
  print(L0)


  CPL1=np.dot(L0,syn1.T)
  print(CPL1)

  L1=nonlin(np.dot(L0,syn1.T))
  print(L1)


  if (L1 >= 0.9 ):
      output=1
  elif (L1 <= 0.2):
      output=0
  else : output=9

  print(output)


  #worksheet = gc.open(2025_DT 的副本").worksheet("input")

  worksheet.update([[output]], 'F1')




[[ -3.86691115  -0.16707528  -0.07027842]
 [  7.40920991  -1.98081406  -2.95002294]
 [-11.77842005  -0.36680751   0.90453073]]
[-3.26440319  6.43803832 -7.25553539]
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409501315
0.11497001897396604
0
[0. 0. 0.]
[0. 0. 0.]
[0.5 0.5 0.5]
-2.0409

APIError: APIError: [429]: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:522309567947'.

In [ ]:
#


import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A



worksheet = gc.open("2025_DT").worksheet("W0")

# get_all_values gives a list of rows.

syn00 = worksheet.get("A1:D3")
syn0=np.array(syn00, dtype=float)
print(syn0)

worksheet = gc.open("2025_DT").worksheet("W1")
syn11 = worksheet.get("A1:C1")
syn1=np.array(syn11[0], dtype=float)
print(syn1)

[]
[-3.26440319  6.43803832 -7.25553539]


In [ ]:
worksheet = gc.open("2025_DT").worksheet("X")
X = worksheet.get("A1:C1")
X=np.array(X[0], dtype=float)
print(X)

[0. 0. 1.]


In [ ]:

CPL0=np.dot(X,syn0.T)
print(CPL0)
L0=nonlin(np.dot(X,syn0.T))
print(L0)

[-0.07027842 -2.95002294  0.90453073]
[0.48243762 0.04973543 0.71187968]


In [ ]:
CPL1=np.dot(L0,syn1.T)
print(CPL1)

L1=nonlin(np.dot(L0,syn1.T))
print(L1)



-6.41974052773718
0.0016264292991147562


In [ ]:
if (L1 >= 0.5 ):
    output=1
elif (L1 <= 0.2):
    output=0
else : output=9

print(output)


0


In [ ]:

worksheet = gc.open("2025_DT").worksheet("X")

worksheet.update([[output]], 'E1')

{'spreadsheetId': '16kaA404egQOEYNpWUKzooOZWZy-20EPRG_RGXwFM7Y4',
 'updatedRange': 'X!E1',
 'updatedRows': 1,
 'updatedColumns': 1,
 'updatedCells': 1}

In [ ]:
[1,2,3]==[1,2,3]

True