<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/neural_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv
import numpy as np
import pandas as pd
url = "https://raw.githubusercontent.com/husthorng/hello-world/neural/trainingdata.csv"
import numpy as np
def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A
# print(nonlin(0,1))

numTag=1   #
hidden_node=3

records = pd.read_csv(url,encoding='utf-8')
#print(records.shape)
inputD=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
#print(inputD.shape)
tagetD=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values
print(inputD)
print(tagetD)
np.random.seed(1)
syn0=2*np.random.random((inputD.shape[1],hidden_node))-1
syn1=2*np.random.random((hidden_node,numTag))-1
# print(syn0)
# print(syn1)
for j in range(1200):
    X=inputD
    L0=nonlin(np.dot(inputD,syn0))
    L1=nonlin(np.dot(L0,syn1))
    #print(L1)
    L1_error=tagetD-L1
    if(j % 10)==0:
        print("Error"+str(np.mean(np.abs(L1_error))))
    #print(L1_error)
    L1_delta=L1_error*nonlin(L1,deriv=True)
    #print(L1_delta)
    L0_error=L1_delta.dot(syn1.T)
    L0_delta=L0_error*nonlin(L0,deriv=True)
    syn1 += L0.T.dot(L1_delta)
    syn0 += inputD.T.dot(L0_delta)
print("output after Training:")
# np.savetxt("syn0.csv", syn0, delimiter=",")
# np.savetxt("syn1.csv", syn1, delimiter=",")
#print(syn0)
df = pd.DataFrame(syn0)
df.to_csv("syn0.csv")
df = pd.DataFrame(syn1)
df.to_csv("syn1.csv")
print(L1)
print(syn0)
print(syn1)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [0]
 [1]
 [1]]
Error0.5108456683181674
Error0.49827517695918466
Error0.48515698572956134
Error0.46118561235577704
Error0.41773650978735105
Error0.35302487124321646
Error0.27568852450850967
Error0.20456877195029624
Error0.15147472336885737
Error0.11508255629042653
Error0.09030563422437295
Error0.07303521590581305
Error0.06061305095351157
Error0.05139640659850054
Error0.04436346311147878
Error0.03886335583125783
Error0.03446951326269466
Error0.03089426368007204
Error0.02793833146133264
Error0.02546024676462694
Error0.02335732624713261
Error0.02155353776719605
Error0.019991564522360124
Error0.018627495043739253
Error0.01742719421824522
Error0.016363774480908165
Error0.015415801939740476
Error0.014566002850663876
Error0.013800316759661174
Error0.013107193754127725
Error0.012477066198851212
Error0.011901946930664032
Error0.011375120289832223
Error0.01089090212351256
Error0.01044445160334045
Error0.010031622372443677
Error0.009648843835298642
Error0

horng@hust.edu.tw

https://chatgpt.com/c/6a90c7ff-cc04-83ee-981e-5d189b279a61

In [ ]:
!pip install -q gspread

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default

creds, _ = default()

gc = gspread.authorize(creds)

https://colab.research.google.com/drive/1PEN2aO1C7y0uO8xeIeexOzSex1qhjq-a?usp=sharing

[neural training](https://docs.google.com/spreadsheets/d/17SfXcwlQCx2O_2XStirVF9j8Q4M5b9PWy4Kb7WOMW9Q/edit?usp=sharing)

In [ ]:
import numpy as np
import pandas as pd

# ==========================================
# Google Sheet ID
# ==========================================

SHEET_ID = "17SfXcwlQCx2O_2XStirVF9j8Q4M5b9PWy4Kb7WOMW9Q"


# ==========================================
# 開啟 Google Sheet
# ==========================================

sh = gc.open_by_key(SHEET_ID)

worksheet = sh.worksheet("DATA")


# ==========================================
# 讀取全部資料
# ==========================================

data = worksheet.get_all_records()

df = pd.DataFrame(data)

print("Google Sheet 資料：")

display(df)

Google Sheet 資料：


,X1,X2,X3,Y
0,0,0,0,0
1,0,0,1,1
2,0,1,0,1
3,0,1,1,0
4,1,0,0,1


In [ ]:
# ==========================================
# Neural Network Input
# ==========================================

X = df[["X1", "X2", "X3"]].values.astype(float)


# ==========================================
# Neural Network Output
# ==========================================

y = df[["Y"]].values.astype(float)


print("X =")

print(X)


print("\ny =")

print(y)


print("\nX shape =", X.shape)

print("y shape =", y.shape)

X =
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]]

y =
[[0.]
 [1.]
 [1.]
 [0.]
 [1.]]

X shape = (5, 3)
y shape = (5, 1)


In [ ]:
# ==========================================
# Neural Network
# 3 Input
# 3 Hidden
# 1 Output
# ==========================================

import numpy as np


# ==========================================
# 固定亂數
# ==========================================

np.random.seed(1)


# ==========================================
# Sigmoid
# ==========================================

def sigmoid(x):
    x = np.clip(x, -500, 500)
    return 1 / (1 + np.exp(-x))


# ==========================================
# Sigmoid 微分
# ==========================================

def sigmoid_derivative(x):

    return x * (1 - x)


# ==========================================
# 初始化權重
# ==========================================

# Input(3) → Hidden(3)

W0 = np.random.uniform(
    -1,
    1,
    (3, 3)
)


# Hidden(3) → Output(1)

W1 = np.random.uniform(
    -1,
    1,
    (3, 1)
)


# ==========================================
# Bias
# ==========================================

# Hidden Layer Bias

b0 = np.zeros((1, 3))


# Output Layer Bias

b1 = np.zeros((1, 1))


# ==========================================
# Training Parameter
# ==========================================

learning_rate = 0.5

epochs = 50000


# ==========================================
# Training
# ==========================================

for epoch in range(epochs):


    # --------------------------------------
    # Forward Propagation
    # --------------------------------------


    # Input → Hidden

    hidden_input = np.dot(X, W0) + b0

    hidden_output = sigmoid(
        hidden_input
    )


    # Hidden → Output

    output_input = np.dot(
        hidden_output,
        W1
    ) + b1


    output = sigmoid(
        output_input
    )


    # --------------------------------------
    # Error
    # --------------------------------------

    error = y - output


    # --------------------------------------
    # Back Propagation
    # --------------------------------------


    # Output Delta

    output_delta = (
        error *
        sigmoid_derivative(output)
    )


    # Hidden Error

    hidden_error = np.dot(
        output_delta,
        W1.T
    )


    # Hidden Delta

    hidden_delta = (
        hidden_error *
        sigmoid_derivative(
            hidden_output
        )
    )


    # --------------------------------------
    # Update W1
    # --------------------------------------

    W1 += (
        learning_rate *
        np.dot(
            hidden_output.T,
            output_delta
        )
    )


    # --------------------------------------
    # Update W0
    # --------------------------------------

    W0 += (
        learning_rate *
        np.dot(
            X.T,
            hidden_delta
        )
    )


    # --------------------------------------
    # Update Bias
    # --------------------------------------

    b1 += (
        learning_rate *
        np.sum(
            output_delta,
            axis=0,
            keepdims=True
        )
    )


    b0 += (
        learning_rate *
        np.sum(
            hidden_delta,
            axis=0,
            keepdims=True
        )
    )


    # --------------------------------------
    # 顯示 Loss
    # --------------------------------------

    if epoch % 5000 == 0:

        loss = np.mean(
            error ** 2
        )

        print(
            "Epoch:",
            epoch,
            "Loss:",
            loss
        )


print("\nTraining Complete")

Epoch: 0 Loss: 0.2489231586689097
Epoch: 5000 Loss: 0.0005150998400639528
Epoch: 10000 Loss: 0.0002266700235131511
Epoch: 15000 Loss: 0.00014407346891390883
Epoch: 20000 Loss: 0.00010526250558038673
Epoch: 25000 Loss: 8.279253127877007e-05
Epoch: 30000 Loss: 6.81644251077879e-05
Epoch: 35000 Loss: 5.7894183516057905e-05
Epoch: 40000 Loss: 5.0292399288538755e-05
Epoch: 45000 Loss: 4.444163814636305e-05

Training Complete


In [ ]:
print("\n==============================")
print("W0")
print("Input → Hidden")
print("==============================")

print(W0)


print("\n==============================")
print("b0")
print("Hidden Bias")
print("==============================")

print(b0)


print("\n==============================")
print("W1")
print("Hidden → Output")
print("==============================")

print(W1)


print("\n==============================")
print("b1")
print("Output Bias")
print("==============================")

print(b1)


W0
Input → Hidden
[[ 1.59200208  2.85073462 -2.00639241]
 [ 4.24092945 -7.17099873 -4.93668278]
 [-7.07100716  4.80771046 -4.66530027]]

b0
Hidden Bias
[[-1.43628832 -1.92109311  0.98531392]]

W1
Hidden → Output
[[10.60429151]
 [10.60915928]
 [-5.75757664]]

b1
Output Bias
[[-4.89308433]]


In [ ]:
# ==========================================
# Prediction
# ==========================================


hidden = sigmoid(
    np.dot(X, W0) + b0
)


output = sigmoid(
    np.dot(hidden, W1) + b1
)


# ==========================================
# Binary Result
# ==========================================

binary_output = (
    output >= 0.5
).astype(int)


# ==========================================
# 建立結果表
# ==========================================

result = pd.DataFrame()


result["X1"] = X[:, 0]

result["X2"] = X[:, 1]

result["X3"] = X[:, 2]


result["Expected"] = y.flatten()


result["Prediction"] = output.flatten()


result["Binary"] = binary_output.flatten()


display(result)

,X1,X2,X3,Expected,Prediction,Binary
0,0.0,0.0,0.0,0.0,0.003358,0
1,0.0,0.0,1.0,1.0,0.993414,1
2,0.0,1.0,0.0,1.0,0.993298,1
3,0.0,1.0,1.0,0.0,0.009921,0
4,1.0,0.0,0.0,1.0,0.998996,1


In [ ]:
# ==========================================
# Convert Neural Network Weight
# to ESP32 C++ Array
# ==========================================


print("\n\n")
print("// =====================================")
print("// Neural Network Weight")
print("// Auto Generated by Google Colab")
print("// Architecture: 3-3-1")
print("// =====================================")


# ==========================================
# W0
# ==========================================

print("\nconst float W0[3][3] = {")

for i in range(3):

    print("  {", end="")

    for j in range(3):

        print(
            f"{W0[i][j]:.8f}f",
            end=""
        )

        if j < 2:
            print(", ", end="")

    if i < 2:
        print("},")
    else:
        print("}")

print("};")


# ==========================================
# B0
# ==========================================

print("\nconst float B0[3] = {")

for i in range(3):

    print(
        f"{b0[0][i]:.8f}f",
        end=""
    )

    if i < 2:
        print(", ", end="")

print("};")


# ==========================================
# W1
# ==========================================

print("\nconst float W1[3] = {")

for i in range(3):

    print(
        f"{W1[i][0]:.8f}f",
        end=""
    )

    if i < 2:
        print(", ", end="")

print("};")


# ==========================================
# B1
# ==========================================

print(
    "\nconst float B1 = "
    f"{b1[0][0]:.8f}f;"
)




// =====================================
// Neural Network Weight
// Auto Generated by Google Colab
// Architecture: 3-3-1
// =====================================

const float W0[3][3] = {
  {1.59200208f, 2.85073462f, -2.00639241f},
  {4.24092945f, -7.17099873f, -4.93668278f},
  {-7.07100716f, 4.80771046f, -4.66530027f}
};

const float B0[3] = {
-1.43628832f, -1.92109311f, 0.98531392f};

const float W1[3] = {
10.60429151f, 10.60915928f, -5.75757664f};

const float B1 = -4.89308433f;


In [ ]:
//neural_networks_3_1_arduino.ino
// https://drive.google.com/file/d/1L52F7ktVJUKTEYK5yJQf8X2ryXfS80F1/view?usp=drive_link
// ==========================================
// ESP32 Neural Network
// Architecture:
// Input  = 3
// Hidden = 3
// Output = 1
// ==========================================

#include <Arduino.h>
#include <math.h>


// ==========================================
// Neural Network Weight
// 請貼入 Colab 訓練後的數值
// ==========================================


// Input → Hidden

const float W0[3][3] = {
  {1.59200208f, 2.85073462f, -2.00639241f},
  {4.24092945f, -7.17099873f, -4.93668278f},
  {-7.07100716f, 4.80771046f, -4.66530027f}
};

const float B0[3] = {
-1.43628832f, -1.92109311f, 0.98531392f};

const float W1[3] = {
10.60429151f, 10.60915928f, -5.75757664f};

const float B1 = -4.89308433f;


// ==========================================
// Sigmoid
// ==========================================

float sigmoid(float x)
{
  return 1.0f /
         (1.0f + exp(-x));
}


// ==========================================
// Neural Network Prediction
// ==========================================

float neuralNetwork(
  float X1,
  float X2,
  float X3
)
{

  // --------------------------------------
  // Input Array
  // --------------------------------------

  float input[3] = {

    X1,

    X2,

    X3

  };


  // --------------------------------------
  // Hidden Layer
  // --------------------------------------

  float hidden[3];


  for (int j = 0; j < 3; j++)
  {

    float sum = B0[j];


    for (int i = 0; i < 3; i++)
    {

      sum += input[i] * W0[i][j];

    }


    hidden[j] = sigmoid(sum);

  }


  // --------------------------------------
  // Output Layer
  // --------------------------------------

  float outputSum = B1;


  for (int i = 0; i < 3; i++)
  {

    outputSum += hidden[i] * W1[i];

  }


  float output = sigmoid(outputSum);


  return output;

}


// ==========================================
// Setup
// ==========================================

void setup()
{

  Serial.begin(115200);


  Serial.println();

  Serial.println(
    "ESP32 Neural Network Start"
  );


  // --------------------------------------
  // Test Input
  // --------------------------------------

  float X1 = 1;

  float X2 = 0;

  float X3 = 1;


  // --------------------------------------
  // Neural Network Prediction
  // --------------------------------------

  float result = neuralNetwork(
    X1,
    X2,
    X3
  );


  Serial.print(
    "Neural Network Output = "
  );


  Serial.println(
    result,
    6
  );


  // --------------------------------------
  // Binary Output
  // --------------------------------------

  if (result >= 0.5)
  {

    Serial.println(
      "Result = 1"
    );

  }

  else
  {

    Serial.println(
      "Result = 0"
    );

  }

}


// ==========================================
// Loop
// ==========================================

void loop()
{

}

SyntaxError: invalid character '→' (U+2192) (1630922969.py, line 19)

In [ ]:
# ==========================================
# 將 Neural Network 權重寫入 Google Sheet
#
# W0 → neural training W0
# B0 → neural training B0
# W1 → neural training W1
# B1 → neural training B1
# ==========================================

import pandas as pd


# ==========================================
# 開啟 Google Sheet
# ==========================================

#sh = gc.open_by_key(17SfXcwlQCx2O_2XStirVF9j8Q4M5b9PWy4Kb7WOMW9Q)


# ==========================================
# 寫入 W0
# ==========================================

try:
    ws_W0 = sh.worksheet("W0")

except:
    ws_W0 = sh.add_worksheet(
        title="W0",
        rows=10,
        cols=10
    )


# 清除舊資料
ws_W0.clear()


# 加入欄位名稱
W0_df = pd.DataFrame(
    W0,
    columns=["H1", "H2", "H3"],
    index=["X1", "X2", "X3"]
)

# 將 index 變成第一欄
W0_df.insert(
    0,
    "Input",
    W0_df.index
)

# 寫入 Google Sheet
ws_W0.update(
    [W0_df.columns.values.tolist()]
    + W0_df.values.tolist()
)


# ==========================================
# 寫入 B0
# ==========================================

try:
    ws_B0 = sh.worksheet("B0")

except:
    ws_B0 = sh.add_worksheet(
        title="B0",
        rows=10,
        cols=10
    )


# 清除舊資料
ws_B0.clear()


B0_df = pd.DataFrame(
    b0,
    columns=["H1", "H2", "H3"]
)


ws_B0.update(
    [B0_df.columns.values.tolist()]
    + B0_df.values.tolist()
)


# ==========================================
# 寫入 W1
# ==========================================

try:
    ws_W1 = sh.worksheet("W1")

except:
    ws_W1 = sh.add_worksheet(
        title="W1",
        rows=10,
        cols=10
    )


# 清除舊資料
ws_W1.clear()


W1_df = pd.DataFrame(
    W1,
    columns=["Output"],
    index=["H1", "H2", "H3"]
)


W1_df.insert(
    0,
    "Hidden",
    W1_df.index
)


ws_W1.update(
    [W1_df.columns.values.tolist()]
    + W1_df.values.tolist()
)


# ==========================================
# 寫入 B1
# ==========================================

try:
    ws_B1 = sh.worksheet("B1")

except:
    ws_B1 = sh.add_worksheet(
        title="B1",
        rows=10,
        cols=10
    )


# 清除舊資料
ws_B1.clear()


B1_df = pd.DataFrame(
    [[b1[0][0]]],
    columns=["Output_Bias"]
)


ws_B1.update(
    [B1_df.columns.values.tolist()]
    + B1_df.values.tolist()
)


# ==========================================
# 完成
# ==========================================

print("===================================")
print("Neural Network Weight 已寫入完成")
print("===================================")

print("W0 → Google Sheet 工作表：W0")
print("B0 → Google Sheet 工作表：B0")
print("W1 → Google Sheet 工作表：W1")
print("B1 → Google Sheet 工作表：B1")

Neural Network Weight 已寫入完成
W0 → Google Sheet 工作表：W0
B0 → Google Sheet 工作表：B0
W1 → Google Sheet 工作表：W1
B1 → Google Sheet 工作表：B1
