<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/neural_hung.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()



gc = gspread.authorize(creds)

worksheet = gc.open("2025_DT hung").worksheet("tr33")
#worksheet = gc.open("2025_DT hung").worksheet("training")
#records = pd.read_excel('https://docs.google.com/spreadsheets/d/e/2PACX-1vT1fsVI46ixmI5Fb8bwTKrhkcWajupllMcaYHv2waOct-gpv3P-Ej0IVQlrUZqAj1rYP45wlUkJKcK2/pub?output=xlsx')
#https://docs.google.com/spreadsheets/d/1cnAI9KTv0NAFCrJ5iHXF0DFSj1LxxvkllSXd6Z5Dtg0/edit?gid=0#gid=0
#neural_networks_3_1_cloud.zip https://drive.google.com/file/d/1pzKNlR7pe5zEOvehfiOT1WJ2_C7pqWw3/view?usp=drive_link

#digital twin.ppt https://docs.google.com/presentation/d/1VDzhRRHciuISuz9JyAyn6pFwY4r7EJdqYgfrvOoG-aE/edit?usp=sharing


rows = worksheet.get_all_values()
rows.pop(0)    #刪除第一列
records1 = np.array(rows, dtype=int)  #將字元['1']換成數字[1]

print(rows)
records = pd.DataFrame(records1) #轉pandas結構

print(records)




np.random.seed()
#1 np.random.seed(7)


numTag=3
hidden_node=13
#1 hidden_node=13

inputD=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
print(inputD.shape)
tagetD=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values
print(inputD)
print(tagetD)

np.random.seed(1) #np.random.seed(1) are the weights that on paper
syn0=2*np.random.random((inputD.shape[1],hidden_node))-1
syn1=2*np.random.random((hidden_node,numTag))-1



def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A




for j in range(12000):
    X=inputD
    L0=nonlin(np.dot(inputD,syn0))
    L1=nonlin(np.dot(L0,syn1))
    #print(L1)
    L1_error=tagetD-L1
    if(j % 100)==0:
        print("Error"+str(np.mean(np.abs(L1_error))))
    #print(L1_error)
    L1_delta=L1_error*nonlin(L1,deriv=True)
    #print(L1_delta)
    L0_error=L1_delta.dot(syn1.T)
    L0_delta=L0_error*nonlin(L0,deriv=True)
    syn1 += L0.T.dot(L1_delta)
    syn0 += inputD.T.dot(L0_delta)

print("output after Training:")
# np.savetxt("syn0.csv", syn0, delimiter=",")
# np.savetxt("syn1.csv", syn1, delimiter=",")
#print(syn0)

df0 = pd.DataFrame(syn0.transpose())
L1=np.where(L1 > 0.9, 1, 0)

df0.to_csv("syn0.csv")
df1 = pd.DataFrame(syn1.transpose())
df1.to_csv("syn1.csv")
print(L1)
print(syn0)
print(syn0.transpose())
print(syn1)

# Open our sheet and add some data.
#https://docs.google.com/spreadsheets/d/1cnAI9KTv0NAFCrJ5iHXF0DFSj1LxxvkllSXd6Z5Dtg0/edit?gid=0#gid=0
worksheet = gc.open("2025_DT hung").worksheet("tr33W0")

worksheet.update_acell('A1', records.shape[1]-numTag)
worksheet.update_acell('B1', hidden_node)
worksheet.update(df0.values.tolist(), 'A2')



worksheet = gc.open("2025_DT hung").worksheet("tr33W1")
worksheet.update(df1.values.tolist(), 'A2')
worksheet.update_acell('A1', numTag)
worksheet.update_acell('B1', hidden_node)

#download arduino file "neural_networks_3_1_cloud.zip" unzip and open it
#https://drive.google.com/file/d/1GrMIwb6K9zBEWT2sf9n1bLoJCJuwZIsY/view?usp=sharing

worksheet = gc.open("2025_DT hung").worksheet("input")
row1 = worksheet.row_values(1)
print(row1)

[['0', '0', '0', '0', '0', '1'], ['1', '0', '0', '0', '1', '0'], ['0', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '0', '1'], ['1', '1', '0', '1', '0', '0'], ['0', '1', '1', '0', '0', '1'], ['1', '1', '1', '1', '0', '0']]
   0  1  2  3  4  5
0  0  0  0  0  0  1
1  1  0  0  0  1  0
2  0  1  0  0  0  1
3  0  0  1  0  0  1
4  1  1  0  1  0  0
5  0  1  1  0  0  1
6  1  1  1  1  0  0
(7, 3)
[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]]
Error0.5104443768193804
Error0.059539510870383
Error0.023275685677133024
Error0.016271510709809187
Error0.014286174915160418
Error0.013804895932390667
Error0.013934367778516775
Error0.014150228560016378
Error0.013973496408384885
Error0.013281181948136291
Error0.012417639246111223
Error0.011735694030712599
Error0.011371689297436741
Error0.011338831580928447
Error0.011615836580898093
Error0.012165128856022653
Error0.012905260465258948
Error0.01367459408603167
Error0.01428326120

In [ ]:
L1

array([[6.39602548e-22, 1.31132844e-04, 9.99934977e-01],
       [1.39973349e-03, 9.98906220e-01, 1.21938327e-06],
       [5.69936605e-04, 1.53044769e-08, 9.99870408e-01],
       [5.34616617e-20, 9.35060873e-09, 9.99999578e-01],
       [9.99062854e-01, 5.58602141e-04, 1.11283256e-04],
       [7.77287904e-04, 2.19444695e-08, 9.99772999e-01],
       [9.99107697e-01, 2.91853490e-05, 2.64496690e-04]])

In [ ]:
binary_array = np.where(L1 > 0.9, 1, 0)
binary_array

array([[0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [ ]:


binary_array = np.where(data > 0.9, 1, 0)

NameError: name 'data' is not defined

In [ ]:
df0

0          1         2
0  -11.945590  -3.472589 -1.807080
1   -3.595074 -32.733545 -8.796217
2  -16.815588  -3.660069 -1.701277
3  -28.041208  -1.362256  0.173388
4  -32.247848  -1.080420 -0.987800
5  -37.000949  -1.196883  0.134369
6  -29.175791  -2.467390  0.834909
7  -37.684951  -1.342225  0.023283
8  -32.100658  33.484047  6.904844
9  -26.292850  -2.257291 -0.464388
10  28.641433 -17.065540 -7.815136
11  -0.094734  -5.587401  2.593254
12 -15.687636  -4.112926 -2.242083

In [ ]:
df0.values.tolist()

[[-0.21704860036541315, 0.13575089413324226, 0.783337787556834],
 [-8.674395941871209, -0.3761548306593547, 1.4270819542462618],
 [7.9590456263171365, -1.574103457858267, -3.5580330848907686]]

In [ ]:
df1.values.tolist()

[[-0.8765681405475877, -7.267930536468156, 6.859364037098843]]

In [ ]:
worksheet = gc.open("2025_DT 的副本").worksheet("input")
rowi = worksheet.row_values(1)
worksheet = gc.open("2025_DT 的副本").worksheet("output")
rowo = worksheet.row_values(1)
if rowo[:3] != rowi[:3] :
  worksheet.insert_row(rowi, 1)
  records1 = np.array(row1, dtype=int)  #將字元['1']換成數字[1]

  inputD = pd.DataFrame(records1) #轉pandas結構
  inputD=inputD.T
  print(inputD.shape)
  L0=nonlin(np.dot(inputD,syn0))
  L1=nonlin(np.dot(L0,syn1))
  print(L1[0][0])

  worksheet.update_acell('E1', L1[0][0])

  if L1[0][0] >= 0.9 :
    worksheet.update_acell('F1', 1)
  else:
    worksheet.update_acell('F1', 0)

In [ ]:
rowo[:3]

['1', '1', '0']

In [ ]:
[[6.39602548e-22 1.31132844e-04 9.99934977e-01]
 [1.39973349e-03 9.98906220e-01 1.21938327e-06]
 [5.69936605e-04 1.53044769e-08 9.99870408e-01]
 [5.34616617e-20 9.35060873e-09 9.99999578e-01]
 [9.99062854e-01 5.58602141e-04 1.11283256e-04]
 [7.77287904e-04 2.19444695e-08 9.99772999e-01]
 [9.99107697e-01 2.91853490e-05 2.64496690e-04]] 數值 大於0.9 設為1，否則設為0

SyntaxError: invalid character '，' (U+FF0C) (ipython-input-4042413838.py, line 7)