<a href="https://colab.research.google.com/github/husthorng/Backpropagation_NN/blob/main/neural_cswp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

WID="15sOASk3jTVCQNy6O-zwed0PXGIiE9JEB4PNc8H3XFcY"

gc = gspread.authorize(creds)

#worksheet = gc.open("2025_DT hung").worksheet("tr33")
worksheet =gc.open_by_key(WID).worksheet("tr33") #2025_DT hung 111husthorng
#worksheet = gc.open("2025_DT hung").worksheet("training")
#records = pd.read_excel('https://docs.google.com/spreadsheets/d/e/2PACX-1vT1fsVI46ixmI5Fb8bwTKrhkcWajupllMcaYHv2waOct-gpv3P-Ej0IVQlrUZqAj1rYP45wlUkJKcK2/pub?output=xlsx')
#https://docs.google.com/spreadsheets/d/1cnAI9KTv0NAFCrJ5iHXF0DFSj1LxxvkllSXd6Z5Dtg0/edit?gid=0#gid=0
#neural_networks_3_1_cloud.zip https://drive.google.com/file/d/1pzKNlR7pe5zEOvehfiOT1WJ2_C7pqWw3/view?usp=drive_link

#digital twin.ppt https://docs.google.com/presentation/d/1VDzhRRHciuISuz9JyAyn6pFwY4r7EJdqYgfrvOoG-aE/edit?usp=sharing


rows = worksheet.get_all_values()
rows.pop(0)    #刪除第一列
records1 = np.array(rows, dtype=int)  #將字元['1']換成數字[1]

print(rows)
records = pd.DataFrame(records1) #轉pandas結構

print(records)




np.random.seed(7)
#1 np.random.seed(7)


numTag=3
hidden_node=13
#1 hidden_node=13

inputD=records.iloc[0:records.shape[0],0:records.shape[1]-numTag].values
print(inputD.shape)
tagetD=records.iloc[:,list(records.shape[1]-np.arange(numTag,0,-1))].values
print(inputD)
print(tagetD)

np.random.seed(1) #np.random.seed(1) are the weights that on paper
syn0=2*np.random.random((inputD.shape[1],hidden_node))-1
syn1=2*np.random.random((hidden_node,numTag))-1



def nonlin(x,deriv=False):
    A=1/(1+np.exp(-x))
    if(deriv==True):
        return (A*(1-A))
    return A




for j in range(12000):
    X=inputD
    L0=nonlin(np.dot(inputD,syn0))
    L1=nonlin(np.dot(L0,syn1))
    #print(L1)
    L1_error=tagetD-L1
    if(j % 100)==0:
        print("Error"+str(np.mean(np.abs(L1_error))))
    #print(L1_error)
    L1_delta=L1_error*nonlin(L1,deriv=True)
    #print(L1_delta)
    L0_error=L1_delta.dot(syn1.T)
    L0_delta=L0_error*nonlin(L0,deriv=True)
    syn1 += L0.T.dot(L1_delta)
    syn0 += inputD.T.dot(L0_delta)

print("output after Training:")
# np.savetxt("syn0.csv", syn0, delimiter=",")
# np.savetxt("syn1.csv", syn1, delimiter=",")
#print(syn0)

df0 = pd.DataFrame(syn0.transpose())
L1=np.where(L1 > 0.9, 1, 0)

df0.to_csv("syn0.csv")
df1 = pd.DataFrame(syn1.transpose())
df1.to_csv("syn1.csv")
print(L1)
print(syn0)
print(syn0.transpose())
print(syn1)

# Open our sheet and add some data.
#https://docs.google.com/spreadsheets/d/1cnAI9KTv0NAFCrJ5iHXF0DFSj1LxxvkllSXd6Z5Dtg0/edit?gid=0#gid=0
#worksheet = gc.open("2025_DT hung").worksheet("tr33W0")
worksheet =gc.open_by_key(WID).worksheet("tr33W0") #2025_DT hung 111husthorng
worksheet.update_acell('A1', records.shape[1]-numTag)
worksheet.update_acell('B1', hidden_node)
worksheet.update(df0.values.tolist(), 'A2')



#worksheet = gc.open("2025_DT hung").worksheet("tr33W1")
worksheet =gc.open_by_key(WID).worksheet("tr33W1") #2025_DT hung 111husthorng
worksheet.update(df1.values.tolist(), 'A2')
worksheet.update_acell('A1', numTag)
worksheet.update_acell('B1', hidden_node)

#download arduino file "neural_networks_3_1_cloud.zip" unzip and open it
#https://drive.google.com/file/d/1GrMIwb6K9zBEWT2sf9n1bLoJCJuwZIsY/view?usp=sharing

worksheet = gc.open("2025_DT hung").worksheet("input")
row1 = worksheet.row_values(1)
print(row1)

[['0', '0', '0', '0', '0', '1'], ['1', '0', '0', '0', '1', '0'], ['0', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '0', '1'], ['1', '1', '0', '1', '0', '0'], ['0', '1', '1', '0', '0', '1'], ['1', '1', '1', '1', '0', '0']]
   0  1  2  3  4  5
0  0  0  0  0  0  1
1  1  0  0  0  1  0
2  0  1  0  0  0  1
3  0  0  1  0  0  1
4  1  1  0  1  0  0
5  0  1  1  0  0  1
6  1  1  1  1  0  0
(7, 3)
[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]]
Error0.5104443768193804
Error0.059539510870383
Error0.023275685677133024
Error0.016271510709809187
Error0.014286174915160418
Error0.013804895932390667
Error0.013934367778516775
Error0.014150228560016378
Error0.013973496408384885
Error0.013281181948136291
Error0.012417639246111223
Error0.011735694030712599
Error0.011371689297436741
Error0.011338831580928447
Error0.011615836580898093
Error0.012165128856022653
Error0.012905260465258948
Error0.01367459408603167
Error0.01428326120